FROM python:3.9.13-alpine3.15

RUN pip3 install flask-restful 
RUN pip install docker
RUN pip install pyyaml

COPY ./vhostbackup/server.py /tmp/server.py
COPY ./docker-compose.yml /tmp/docker-compose.yml

CMD python /tmp/server.py