# TODO: move most logic from all Dockerfiles to this file
- name: Main playbook
  hosts: localhost
  gather_facts: true
  tasks:
    - name: install pip
      community.docker.docker_container_exec:
        container: startup
        command: apt-get install python3-pip -y

    - name: install required aws-related libs
      community.docker.docker_container_exec:
        container: startup
        command: pip install boto3

    - name: Update apt cache
      community.docker.docker_container_exec:
        container: vhost1
        command: apt-get update

    - name: Create aws credentials & config direectory
      shell: mkdir -p /root/.aws

    - name: Set AWS config
      shell: |
        echo "[default]
        region = us-west-2" > /root/.aws/config

    # Should read from SecretsManager or environment variable
    - name: Set AWS credentials
      shell: |
        echo "[default]
        aws_access_key_id = ###############
        aws_secret_access_key = ###############" > /root/.aws/credentials

    - name: Create S3 bucket for document storage
      amazon.aws.s3_bucket:
        name: dev-document-22222
        region: us-west-2
        state: present
        encryption: "AES256"
        public_access:
          block_public_acls: true
          block_public_policy: true
          ignore_public_acls: true
      register: url_output
    - debug: var=stdd

    # - name: Install additional binaries
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: apt-get install sed wget curl unzip -y
    #   register: result

    # - name: Download WordPress
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: wget -O  /tmp/latest.zip https://wordpress.org/latest.zip
    #   register: result

    # - name: Extract WordPress to /var/www/html
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: unzip -o /tmp/latest.zip -d /var/www/html

    # - name: Rename wp-config
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

    # This would be more secure with SecretsManager
    # - name: Set database name
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: sed -i "s/database_name_here/wordpress/g" /var/www/html/wordpress/wp-config.php
    #   register: result

    # - name: Set database username
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: sed -i "s/username_here/wordpress/g" /var/www/html/wordpress/wp-config.php

    # - name: Set database password
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: sed -i "s/password_here/wordpress/g" /var/www/html/wordpress/wp-config.php

    # - name: Set database host
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: sed -i "s/localhost/database/g" /var/www/html/wordpress/wp-config.php

    - name: Status of document system deployment
      ansible.builtin.debug:
        msg: "{{ result }}"
