- name: Main playbook
  hosts: localhost
  gather_facts: true
  strategy: ansible.builtin.free

  vars:
    s3BucketName: "dev0-document-storage"

    # AWS credentials are sensitive and should not be committed - preferably fetched from SecretsManager or passed to ansible
    awsAccessKeyId: AKIASLBVYQRNJ6TGXO6H
    awsSecretAccessKey: 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

  tasks:
    - name: Update all containers
      ansible.builtin.import_tasks: update-containers.yml

    - name: Provision S3 credentials
      ansible.builtin.import_tasks: provision-document-s3-credentials.yml

    - name: Create S3 bucket for document storage
      amazon.aws.s3_bucket:
        name: "{{s3BucketName}}"
        region: us-west-2
        state: present
        encryption: "AES256"
        public_access:
          block_public_acls: true
          block_public_policy: true
          ignore_public_acls: true
      register: stdout
    - debug: var=stdout

    - name: Setup document microservice
      ansible.builtin.import_tasks: setup-document-microservice.yml

    - name: Post-jobs [document-microservice]
      community.docker.docker_container_exec:
        container: document-microservice
        command: npm doctor
